Hello COM & Resize
GraphicsProgramming/learnd3d11 pull request #33
Opened 2022-02-23 21:50 UTC by AlexB8675

2022-02-23 23:14 UTC, deccer requested changes
Just a few things, but feedback/opinion welcome and don't apologise :D

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/Application.hpp
> +    [[nodiscard]] GLFWwindow* GetWindow() const;
I am not a fan of this formatting style tbh. BUT dont worry, leave it as is for now, we are working on `.clangformat`

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/Assets/Shaders/Main.vs.hlsl
> +struct vs_in {
Same applies to hlsl... formatting is tbd

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    glfwSetWindowUserPointer(GetWindow(), this);
Hmm yeah, I fink, I would like this glfw stuff contained in `Application`.

Could you introduce a virtual method in `Application` like `WindowResized` set it up as the callback there, and just overwrite `WindowResized` here in HelloXXX. That would keep dependencies separate

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    DXGI_SWAP_CHAIN_DESC swapchainInfo;
Hmmmm I also think we should init these descriptors with `= {};` just in case, probably a good exercise anyway to do it that way

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +        D3D_COMPILE_STANDARD_FILE_INCLUDE,
Ah include handlers... I think it makes sense to cover them at some point in time as well, further down the road :) as an appendix or so

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +        { {  0.0f,  0.5f, 0.0f }, { 0.25f, 0.39f, 0.19f } },
I am not sure if we talked about it, or not, we probably should as a discussion/vote, how we want to initialize things, in a more "obvious" fashion like 

`new VertexPositionColor{ ... }` or.. ah that reminds me, I am quite fond of explicitly named VertexFormat constructs... like VertexPositionColor in this very instance. Would you mind renaming `VertexFormat`?  or how do you feel about it?

(You only have so many vertexformat in your game/engine going, i am aware of that, but you still have a few differnt ones to deal with, be it for the FST/Debug Lights/BoundingBoxes etc... (ignoring vertexpulling for now))

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    bufferInfo.ByteWidth = sizeof vertices;
please with parenthesis :)

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    bufferInfo.ByteWidth = sizeof indices;
same here, with parenthesis please

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    auto* application = static_cast<HelloCOMApplication*>(glfwGetWindowUserPointer(window));
Yeah if we can hide that away in Application that would be neat. 

and introduce Setters for Width/Height in Application might make sense too now that I am looking at this blob here.

2022-02-23 23:14 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    _deviceContext->OMSetRenderTargets(1, _renderTarget.GetAddressOf(), nullptr);
Hmm can you check with 2-HelloFroge's deviceContext->XXX calls? i think i put them in the order of how its being used - pipeline wise, and I think it makes sense to show the user the same thing, might make things a little easier, once we explain dx11's render pipeline

2022-02-23 23:28 UTC, AlexB8675 commented
Thank you for your feedback, I'm on it

2022-02-23 23:45 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    swapchainInfo.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;
I think we should also switch to the FLIP model, since we target mainly win10.

2022-02-23 23:46 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    swapchainInfo.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;
Also while reading that one thing, do you mind prefixing all the enums with their enum class too (i know its not real enum classes, but i would feel more at ease lol. similar to 2-HelloFroge does

2022-02-24 00:11 UTC, deccer commented on src/Cpp/1-getting-started/14-HelloCOM/HelloCOM.cpp
> +    swapchainInfo.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;
FLIP model doesnt support SRGB output formats, only`DXGI_FORMAT_R16G16B16A16_FLOAT, DXGI_FORMAT_B8G8R8A8_UNORM, DXGI_FORMAT_R8G8B8A8_UNORM, DXGI_FORMAT_R10G10B10A2_UNORM`

2022-02-24 00:21 UTC, AlexB8675 commented
All the changes have been implemented, please let me know if I missed something or there's anything else to change

2022-02-24 00:38 UTC, deccer approved these changes
LGTM

2022-02-24 00:49 UTC, merged